#!/bin/sh

curl -s -o /dev/null -w "%{http_code}\n" "https://api.github.com/repos/0111b/Conf"
curl -s -o /dev/null -w "%{http_code}\n" "https://raw.githubusercontent.com/0111b/Conf/master/Package.swift"
curl -s -o /dev/null -w "%{http_code}\n" "https://api.github.com/repos/0111b/JSONDecoder-Keypath"
curl -s -o /dev/null -w "%{http_code}\n" "https://raw.githubusercontent.com/0111b/JSONDecoder-Keypath/master/Package.swift"
curl -s -o /dev/null -w "%{http_code}\n" "https://api.github.com/repos/0x7fs/countedset"
curl -s -o /dev/null -w "%{http_code}\n" "https://raw.githubusercontent.com/0x7fs/countedset/master/Package.swift"
curl -s -o /dev/null -w "%{http_code}\n" "https://api.github.com/repos/0xacdc/XCFSodium"
curl -s -o /dev/null -w "%{http_code}\n" "https://raw.githubusercontent.com/0xacdc/XCFSodium/master/Package.swift"
curl -s -o /dev/null -w "%{http_code}\n" "https://api.github.com/repos/0xdeadp00l/bech32"
curl -s -o /dev/null -w "%{http_code}\n" "https://raw.githubusercontent.com/0xdeadp00l/bech32/master/Package.swift"
curl -s -o /dev/null -w "%{http_code}\n" "https://api.github.com/repos/1024jp/GzipSwift"
curl -s -o /dev/null -w "%{http_code}\n" "https://raw.githubusercontent.com/1024jp/GzipSwift/develop/Package.swift"
curl -s -o /dev/null -w "%{http_code}\n" "https://api.github.com/repos/1024jp/WFColorCode"
curl -s -o /dev/null -w "%{http_code}\n" "https://raw.githubusercontent.com/1024jp/WFColorCode/develop/Package.swift"
curl -s -o /dev/null -w "%{http_code}\n" "https://api.github.com/repos/10clouds/ParticlePullToRefresh-iOS"
curl -s -o /dev/null -w "%{http_code}\n" "https://raw.githubusercontent.com/10clouds/ParticlePullToRefresh-iOS/master/Package.swift"
curl -s -o /dev/null -w "%{http_code}\n" "https://api.github.com/repos/123flo321/pogoprotos-swift"
curl -s -o /dev/null -w "%{http_code}\n" "https://raw.githubusercontent.com/123flo321/pogoprotos-swift/master/Package.swift"
curl -s -o /dev/null -w "%{http_code}\n" "https://api.github.com/repos/1904labs/ios-test-utils"
curl -s -o /dev/null -w "%{http_code}\n" "https://raw.githubusercontent.com/1904labs/ios-test-utils/master/Package.swift"
